# Numpy Overview

* Scientific computing package for Python  
* Arrays are the fundamental elements
* Methods to manipulate and perform mathematical operations on arrays and matrices
* Documentation: https://docs.scipy.org/doc/

# Import the Numpy Package

* Must import numpy package before use
* Import as 'np' and then call using np.<>

In [1]:
import numpy as np

# Create Basic Arrays

In [2]:
A = np.array([[1,2,3]]); print(A)

[[1 2 3]]


In [3]:
B = np.array([[1,2,3],[4,5,6],[7,8,9]]); print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
C = np.zeros((2,1)); print(C)

[[ 0.]
 [ 0.]]


In [5]:
D = np.ones((1,3)); print(D)

[[ 1.  1.  1.]]


In [6]:
E = np.random.randn(3,3); print(E)

[[-0.4796775  -0.64888375  0.23331211]
 [ 0.15458602 -1.26739971  0.0986138 ]
 [-0.9778446   1.11417947 -0.35799954]]


# Array Indexing

In [7]:
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
B[0]

array([1, 2, 3])

In [9]:
B[0,0]

1

In [10]:
B[2,2]

9

In [11]:
B[:,0]

array([1, 4, 7])

# Array Attributes

In [12]:
print(B.dtype)
print(B.shape)
print(B.ndim)
print(B.size)

int32
(3, 3)
2
9


# Array Methods

In [13]:
B.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
B.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
B.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [16]:
B.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
A.nonzero()

(array([0, 0, 0], dtype=int32), array([0, 1, 2], dtype=int32))

# Array Calcuations

In [18]:
A

array([[1, 2, 3]])

In [19]:
A.min()

1

In [20]:
A.max()

3

In [21]:
A.sum()

6

In [22]:
A.mean()

2.0

In [23]:
A.var()

0.66666666666666663

In [24]:
A.std()

0.81649658092772603

# Array Arithmetic

* numpy performs element-wise arithmetic

In [25]:
A

array([[1, 2, 3]])

In [26]:
A*A

array([[1, 4, 9]])

In [27]:
A**A

array([[ 1,  4, 27]], dtype=int32)

In [28]:
A/A

array([[ 1.,  1.,  1.]])

In [29]:
A-A

array([[0, 0, 0]])

In [30]:
A+A

array([[2, 4, 6]])

In [31]:
A<B

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [32]:
A==B

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]], dtype=bool)